chat/urls.py
from .views import (
    CreateChatView,
    UserChatsView,
    DialogChatView,
)

from django.urls import path

app_name = "chat"

urlpatterns = [
    path("chats/", UserChatsView.as_view(), name="chats-home"),
    path('chat/<str:chatname>', DialogChatView.as_view(), name='chats-dialog'),
    path('chat/create/<str:who>/<str:_with>',CreateChatView.as_view(),name='chats-create')
]

instagram/urls.py
from .views import (
    AboutView,
    LikeComment,
    PostCreateView,
    HomeView,
    PostDetailView,
    SavePost,
    SavedPostsView,
    UserLikedPostsView,
    UserPostListView,
    PostUpdateView,
    PostDeleteView,
    LikeView,
    GlobalPostView,
    SearchUser,
    TagPostsView,
    SearchTag
)
from django.urls import path
app_name = "instagram"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("post/new/", PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path('user/<str:username>/', UserPostListView.as_view(), name="user-posts"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post-update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
    path("like/", LikeView.as_view(), name="like"),
    path('explore', GlobalPostView.as_view(), name="explore"),
    path('usearch/', SearchUser.as_view(), name='search-user'),
    path('tsearch/', SearchTag.as_view(), name='search-tag'),
    path('save/', SavePost.as_view(), name="save"),
    path('post/saved/', SavedPostsView.as_view(), name="post-saved"),
    path('likecom/', LikeComment.as_view(), name='like-com'),
    path('liked/', UserLikedPostsView.as_view(), name='post-liked'),
    path('post/tag/<str:tag>/', TagPostsView.as_view(), name='post-tag'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("instagram.urls")),
    path('', include("users.urls")),
    path('', include("chat.urls")),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from .views import (
    CreateUserView,
    LoginView,
    UserFollowingView,
    UserSettingsView,
    FollowUserView,
    UserProfileView,
    UserFollowerView
)
from django.urls import path

app_name = "user"

urlpatterns = [
    path("register/", CreateUserView.as_view(), name="register"),
    path("profile/<str:username>", UserProfileView.as_view(), name="profile"),
    path("follow/", FollowUserView.as_view(), name='follow'),
    path('settings/', UserSettingsView.as_view(), name="settings"),
    path('login/',LoginView.as_view(),name="login"),
    path('followers/<str:username>',UserFollowerView.as_view(),name="followers"),
    path('following/<str:username>',UserFollowingView.as_view(),name="following"),
]

instagram/models.py
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.postgres.fields import ArrayField


class Like(models.Model):
    user = models.ForeignKey(User, related_name="likes",
                             on_delete=models.CASCADE)
    # Generic foreign key
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')


class Post(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = models.ImageField(upload_to="post_pics", default="default.jpg")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author")
    likes = GenericRelation(Like)
    date_posted = models.DateTimeField(default=timezone.now)
    tags = ArrayField(models.CharField(max_length=40), default=list)

    def __str__(self):
        return f"Post by {self.author}"

    @property
    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse("instagram:post-detail", kwargs={"pk": self.pk})


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    likes = GenericRelation(Like)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"Comment on {self.post}"

    @property
    def total_likes(self):
        return self.likes.count()


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

instagram/forms.py
from django import forms
from .models import Comment, Post


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'tags']

    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'id': 'title',
            'placeholder': 'Title'
        }
    ))

    content = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'id': 'content',
            'rows': 3,
            'placeholder': 'Your content here'
        }
    ))
    image = forms.FileField(widget=forms.FileInput(
        attrs={
            'class': 'form-control',
            'type': 'file',
            'id': 'image'
        }
    ))
    tags = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'id': 'tags',
            'placeholder': 'yourtaghere anothertaghere'
        }
    ), required=False)

    def clean_tags(self):
        if self.cleaned_data['tags']:
            tags = self.cleaned_data['tags']
            return tags.split()
        return []


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    content = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write your comment',
            'rows': 2,
            'columns': 30,
            'type': 'submit',
            'id': 'commentMsg'
        }
    ))

instagram/views.py
from typing import Any, Dict, List
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.views.generic import (
    View, ListView, DetailView, CreateView, UpdateView, DeleteView
)
from .forms import CommentForm, CreatePostForm
from .models import Comment, Post, Like, Tag
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.core.paginator import Paginator


class HomeView(LoginRequiredMixin, ListView):

    def get(self, request, *args, **kwargs):
        posts = []
        # список постов пользователей, НА которых подписан пользователь
        for u in request.user.profile.following.all():
            posts.extend(Post.objects.filter(author=u).all())
        return render(
            request,
            "instagram/home.html",
            context={
                'posts': posts,
                'post_type': 'following user posts'
            }
        )


class PostCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = CreatePostForm()
        return render(
            request,
            'instagram/post_form.html',
            {
                'form': form
            }
        )

    def post(self, request, *args, **kwargs):
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            tags = request.POST.get('tags')
            for tag_name in tags.split():
                if not Tag.objects.filter(name=tag_name).exists():
                    Tag.objects.create(name=tag_name)
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'New Post!')
            return HttpResponseRedirect(
                reverse('instagram:post-detail', kwargs={"pk": post.pk})
            )
        return self.get(request)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.filter(id=pk).first()
        if post.author != request.user:
            return HttpResponseRedirect(reverse('instagram:home'))
        form = CreatePostForm(instance=post)
        return render(
            request,
            'instagram/post_form.html',
            {
                'form': form
            }
        )

    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.filter(id=pk).first()
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            tags = request.POST.get('tags')
            for tag_name in tags.split():
                if not Tag.objects.filter(name=tag_name).exists():
                    Tag.objects.create(name=tag_name)
            form.save()
            return HttpResponseRedirect(
                reverse('instagram:post-detail', kwargs={"pk": post.pk})
            )
        return self.get(request, pk)

    def test_func(self, pk):
        post = Post.objects.filter(id=pk).first()
        return self.request.user == post.author


class PostDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.filter(id=pk).first()
        comments = post.comments.all()
        return render(
            request,
            "instagram/post_detail.html",
            context={
                'object': post,
                'form': CommentForm(),
                'comments': comments,
            }
        )

    def post(self, request, pk, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = Post.objects.filter(id=pk).first()
            comment.save()
            messages.success(request, message="Commented!")
            return HttpResponseRedirect(reverse('instagram:post-detail', kwargs={"pk": pk}))


class AboutView(View):

    def get(self, request, *args, **kwargs):
        return render(request, "instagram/about.html")


class UserPostListView(ListView):
    model = Post
    template_name = "instagram/user_posts.html"
    context_object_name = "posts"

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get("username"))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class LikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        id = int(request.POST.get('postid'))
        post = get_object_or_404(Post, id=id)
        post_object_type = ContentType.objects.get_for_model(post)
        like_obj = Like.objects.filter(
            content_type=post_object_type, object_id=post.id, user=request.user
        )
        if like_obj.exists():
            liked = False
            like_obj.delete()
        else:
            liked = True
            like = Like.objects.create(
                content_type=post_object_type, object_id=post.id, user=request.user)
            like.save()

        result = post.total_likes
        post.save()

        return JsonResponse({'result': result, "liked": liked})


class LikeComment(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        id = int(request.POST.get('commentid'))
        comment = get_object_or_404(Comment, id=id)
        comment_object_type = ContentType.objects.get_for_model(comment)
        like_obj = Like.objects.filter(
            content_type=comment_object_type, object_id=comment.id, user=request.user
        )
        if like_obj.exists():
            liked = False
            like_obj.delete()
        else:
            liked = True
            like = Like.objects.create(
                content_type=comment_object_type, object_id=comment.id, user=request.user
            )
            like.save()
        result = comment.total_likes
        comment.save()
        return JsonResponse({'result': result, 'liked': liked})


class GlobalPostView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all().order_by('-date_posted')
        return render(
            request,
            "instagram/home.html",
            context={
                'posts': posts,
            }
        )


class SavePost(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        id = int(request.POST.get('postid'))
        post = get_object_or_404(Post, id=id)
        if post.profiles.filter(id=request.user.id).exists():
            post.profiles.remove(request.user.profile)
            saved = False
        else:
            post.profiles.add(request.user.profile)
            saved = True
        post.save()
        return JsonResponse({'saved': saved})


class SavedPostsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        p = Post.objects.all()
        posts = []
        for post in p:
            if post.profiles.filter(user=request.user).exists():
                posts.append(post)
        return render(
            request,
            "instagram/home.html",
            context={
                "posts": posts,
                'post_type': 'saved posts'
            }
        )


class SearchUser(View):
    def post(self, request, *args, **kwargs):
        name = request.POST.get('name').replace('@', '')
        users = User.objects.filter(username__contains=name).all()
        data = [user.username for user in users]
        return JsonResponse({'users': data})


class SearchTag(View):
    def post(self, request, *args, **kwargs):
        tag_name = request.POST.get('tag_name').replace('#', '')
        tags = Tag.objects.filter(name__startswith=tag_name).all()
        return JsonResponse({'tags': [tag.name for tag in tags]})


class UserLikedPostsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        post_object_type = ContentType.objects.get_for_model(Post)
        posts = []
        for post in Post.objects.all():
            if Like.objects.filter(content_type=post_object_type, object_id=post.id, user=request.user).exists():
                posts.append(post)
        return render(
            request,
            "instagram/home.html",
            {'posts': posts, 'post_type': 'liked posts'}
        )


class TagPostsView(LoginRequiredMixin, View):
    def get(self, request, tag):
        posts = Post.objects.filter(tags__contains=[tag])
        return render(
            request,
            "instagram/home.html",
            context={
                'posts': posts,
            }
        )

instagram/templates/instagram/about.html
{% extends 'instagram/layout.html' %}
{% block content %}
<h2>About Page</h2>
{% endblock content %}

instagram/templates/instagram/home.html
{% extends 'instagram/layout.html' %} {% block content %} {% if not posts %}
{%if post_type %}
<h2>You haven't got {{post_type}}. Try to explore them!</h2>
{% else %}
<h2>There are no posts(</h2>
{% endif %} {% endif %} {% for object in posts %} {% include
'instagram/_post.html' %} {% endfor %} {% endblock content %}

instagram/templates/instagram/layout.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
  {% load static %}
  <!-- <script src="{% static 'js/jquery-3.6.0.min.js' %}" text="text/javascript"></script> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/card.css' %}">
  <link rel="stylesheet" href="{% static 'css/table.css' %}">
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
  <title>Bloguru</title>
</head>

<body>
  <style>
    body {
      font-family: Georgia, 'Times New Roman', Times, serif
    }
  </style>
  <!-- Навигация -->
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'instagram:home' %}">Bloguru</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <div class="dropdown">
                <img src="{{ request.user.profile.image.url }}" alt="..."
                  style="width: 36px;height: 36px;border-radius: 50%;margin-right: 5px;" type="button"
                  id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li><a class="nav-item nav-link" href="{% url 'user:profile' request.user.username %}">Profile</a>
                  </li>
                  <li><a class="nav-item nav-link" href="{% url 'instagram:post-create' %}">New Post</a></li>
                  <li><a class="nav-item nav-link" href="{% url 'user:settings' %}">Settings</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="nav-item nav-link" href="{% url 'logout' %}">Sign Out</a></li>
                </ul>
              </div>
            </li>
            {% endif %}
            <li class="nav-item">
              <form class="d-flex" style="margin-top:2px">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" id="isearch"
                  style="position: relative;" data-toggle="dropdown">
                <div class="dropdown">
                  <ul class="dropdown-menu" role="menu" aria-labelledby="menu1" id="drp">
                  </ul>
                </div>
              </form>
            </li>
            {% if user.is_authenticated %}
            {% else %}
            <li class="nav-item">
              <a class="nav-item nav-link" href="{% url 'user:register' %}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link" href="{% url 'user:login' %}">Sign In</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="col-md-8">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{message.tags}}">
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
      {% block content %}{% endblock %}
    </div>
    {% if user.is_authenticated %}
    <div class="col-md-4">
      <div class="content-section">
        <div class="row">
          <div class="col-sm" style="max-width: 45px;margin-left: 3%;">
            <img src="{{ request.user.profile.image.url }}" alt="..."
              style="width: 36px;height: 36px;overflow: hidden;border-radius: 50%;margin-right: 5px;">
          </div>
          <div class="col-sm" style="max-width:fit-content">
            <a href="{% url 'user:profile' request.user.username %}" style="text-decoration: none;color: black;"><b
                style="font-size:medium;">{{request.user.username}}</b></a><br>
            <small class="text-muted">{{request.user.first_name}}</small>
          </div>
        </div>
        <p class='text-muted'>
        <ul class="list-group">
          <li class="list-group-item list-group-item-light"><a href="{% url 'instagram:explore' %}"
              style="text-decoration: none;color:black">Explore</a></li>
          <li class="list-group-item list-group-item-light"><a href="{% url 'user:followers' request.user.username %}"
              style="text-decoration: none;color:black">Followers</a></li>
          <li class="list-group-item list-group-item-light"><a href="{% url 'user:following' request.user.username %}"
              style="text-decoration: none;color:black">Following</a></li>
          <li class="list-group-item list-group-item-light"><a href="{% url 'instagram:post-liked' %}"
              style="text-decoration: none;color:black">Liked Posts</a></li>
          <li class="list-group-item list-group-item-light"><a href="{% url 'instagram:post-saved' %}"
              style="text-decoration: none;color:black">Saved Posts</a></li>
        </ul>
        </p>
      </div>
    </div>
    {% endif %}
  </main>
  {% block errors %}
  {% endblock errors %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script> -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>
<script>
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = jQuery.trim(cookies[i]);
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  //
  // 
  function redirectp(id) {
    loc = window.location.href.split('/');
    tloc = '';
    for (let i = 0; i < 3; i++) {
      const element = loc[i];
      tloc += loc[i] + '/';
    }
    window.location.replace(tloc + 'profile/' + id.innerHTML);
  }
  function redirectt(id) {
    loc = window.location.href.split('/');
    tloc = '';
    for (let i = 0; i < 3; i++) {
      const element = loc[i];
      tloc += loc[i] + '/';
    }
    tag_name = id.innerHTML
    tag_name = tag_name.slice(1, tag_name.length)
    console.log(tag_name)
    window.location.replace(tloc + 'post/tag/' + tag_name);
  }
  // ajax
  $(document).on('keyup', '#isearch', (e) => {
    let text = $("#isearch").val()
    if (text[0] === '@' || text[0] === '#') {
      if (text[0]==='@') {
        $.ajax({
          type: 'POST',
          url: '{% url "instagram:search-user" %}',
          data: {
            name: text,
            csrfmiddlewaretoken: getCookie('csrftoken'),
            action: 'post'
          },
          success: (json) => {
            search = document.querySelector('#drp')
            $(search).empty();
            json['users'].forEach(element => {
              arr = ['<li role="presentation"><a role="menuitem" class="btn" onclick="redirectp(this)" tabindex="-1" id="',
                element,
                '">',
                element,
                '</a></li>'
              ]
              search.insertAdjacentHTML(
                'beforeend',
                arr.join("")
              );
            });
          },
          error: function (xhr, errmsg, err) {

          }
        });
      }
      // tag search
      else {
        $.ajax({
          type: 'POST',
          url: '{% url "instagram:search-tag" %}',
          data: {
            tag_name: text,
            csrfmiddlewaretoken: getCookie('csrftoken'),
            action: 'post'
          },
          success: (json) => {
            search = document.querySelector('#drp')
            $(search).empty();
            json['tags'].forEach(element => {
              arr = ['<li role="presentation"><a role="menuitem" class="btn" onclick="redirectt(this)" tabindex="-1" id="',
                element,
                '">#',
                element,
                '</a></li>'
              ]
              search.insertAdjacentHTML(
                'beforeend',
                arr.join("")
              );
            });
          },
          error: function (xhr, errmsg, err) {

          }
        });
      }

    }

  })
  function getVal() {
    const val = document.querySelector('input').value;
    console.log(val);
  }
</script>

</html>

instagram/templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {%csrf_token%}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Delete Post
            </legend>
            <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'instagram:post-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}
{% load instagram_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            {{ form.title }}
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            {{form.content}}
        </div>
        <div class="mb-3">
            <label for="image" class="form-label">Image</label>
            {{form.image}}
        </div>
        <div class="mb-3">
            <label for="tags" class="form-label">Tags <small class="text-muted">(enter without "#" and with spaces for
                    many tags)</small></label>
            <!-- FIXME tag displaying -->
            {{form.tags}}
        </div>
        <button type="submit" class="btn btn-primary">Post</button>
    </form>
</div>
{% endblock content %}

instagram/templates/instagram/user_posts.html
{% extends 'instagram/layout.html' %}
{% block content %}
{% for object in posts %}
{% include 'instagram/_post.html' %}
{% endfor %}
{% endblock content %}