chat/urls.py
from .views import (
    CreateChatView,
    UserChatsView,
    DialogChatView,
)

from django.urls import path

app_name = "chat"

urlpatterns = [
    path("chats/", UserChatsView.as_view(), name="chats-home"),
    path('chat/<str:chatname>', DialogChatView.as_view(), name='chats-dialog'),
    path('chat/create/<str:who>/<str:_with>',CreateChatView.as_view(),name='chats-create')
]

instagram/urls.py
from .views import (
    AboutView,
    LikeComment,
    PostCreateView,
    HomeView,
    PostDetailView,
    SavePost,
    SavedPostsView,
    UserLikedPostsView,
    UserPostListView,
    PostUpdateView,
    PostDeleteView,
    LikeView,
    GlobalPostView,
    SearchUser,
    TagPostsView,
    SearchTag
)
from django.urls import path
app_name = "instagram"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("post/new/", PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path('user/<str:username>/', UserPostListView.as_view(), name="user-posts"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post-update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
    path("like/", LikeView.as_view(), name="like"),
    path('explore', GlobalPostView.as_view(), name="explore"),
    path('usearch/', SearchUser.as_view(), name='search-user'),
    path('tsearch/', SearchTag.as_view(), name='search-tag'),
    path('save/', SavePost.as_view(), name="save"),
    path('post/saved/', SavedPostsView.as_view(), name="post-saved"),
    path('likecom/', LikeComment.as_view(), name='like-com'),
    path('liked/', UserLikedPostsView.as_view(), name='post-liked'),
    path('post/tag/<str:tag>/', TagPostsView.as_view(), name='post-tag'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("instagram.urls")),
    path('', include("users.urls")),
    path('', include("chat.urls")),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from .views import (
    CreateUserView,
    LoginView,
    UserFollowingView,
    UserSettingsView,
    FollowUserView,
    UserProfileView,
    UserFollowerView
)
from django.urls import path

app_name = "user"

urlpatterns = [
    path("register/", CreateUserView.as_view(), name="register"),
    path("profile/<str:username>", UserProfileView.as_view(), name="profile"),
    path("follow/", FollowUserView.as_view(), name='follow'),
    path('settings/', UserSettingsView.as_view(), name="settings"),
    path('login/',LoginView.as_view(),name="login"),
    path('followers/<str:username>',UserFollowerView.as_view(),name="followers"),
    path('following/<str:username>',UserFollowingView.as_view(),name="following"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from instagram.models import Post

from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")
    bg_image = models.ImageField(
        default="bg_default.jpg", upload_to="bg_images")
    followers = models.ManyToManyField(
        User, blank=True, related_name='user_followers', symmetrical=False)
    following = models.ManyToManyField(
        User, blank=True, related_name='user_following', symmetrical=False)
    saved_posts = models.ForeignKey(
        Post, on_delete=models.CASCADE, blank=True, null=True, related_name='profiles')

    def __str__(self):
        return f"{self.user.username} Profile {self.followers.count()} {self.following.count()}"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 512 or img.width > 512 or img.width != img.height:
            out = (512, 512)
            i = img.resize(out)
            i.save(self.image.path)

    @ property
    def followers_count(self):
        return self.followers.count()

    @ property
    def following_count(self):
        return self.following.count()

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import Profile
from PIL import Image


class CreateUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
        'id': 'floatingInput',
    }), max_length=20, required=True)
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'First name',
        'id': 'floatingInput',
    }), max_length=20, required=True)
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'type': 'email',
        'class': 'form-control',
        'placeholder': 'example@example.com'
    }), required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'type': 'password',
        'placeholder': 'Password'
    }), required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'type': 'password',
        'placeholder': 'Password'
    }), required=True)

    def clean_username(self):
        username = self.cleaned_data['username']

        if User.objects.filter(username=username).exists():
            raise ValidationError(
                f'User with username "{username}" already exists')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError(
                f'User with email {email} already exists.'
            )
        return email

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'password1', 'password2']


class LoginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
    }), required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'type': 'password',
    }), required=True)

    class Meta:
        model = User
        fields = ['username', 'password']

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                f'User with username "{username}" not found in the system.')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Wrong password.")
        return self.cleaned_data


class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'bg_image']
    # FIXME nice cropping image (see Django-crop-images)

users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.contenttypes.models import ContentType
from django.http.response import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import (
    CreateUserForm,
    UpdateProfileForm,
    UpdateUserForm,
    LoginForm
)
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
app_name = "user"


class LoginView(View):
    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(
            request,
            "users/login.html",
            {'form': form}
        )

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(
                username=username,
                password=password
            )
            if user:
                login(request, user)
                return HttpResponseRedirect('/')
        return render(
            request,
            'users/login.html',
            {
                'form': LoginForm(),
                'errors': form.non_field_errors()
            }
        )


class CreateUserView(View):

    def get(self, request, *args, **kwargs):
        form = CreateUserForm()

        return render(request, 'users/register.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, message="Successfully created")
            return redirect('user:login')
        else:
            email_errors, username_errors, password_errors = ([], [], [])
            if form.errors.get('email'):
                email_errors = [error for error in form.errors.get('email')]
            if form.errors.get('username'):
                username_errors = [
                    error for error in form.errors.get('username')]
            if form.errors.get('password2'):
                password_errors = [
                    error for error in form.errors.get('password2')]
        return render(
            request,
            'users/register.html',
            {
                'form': CreateUserForm(),
                'email_errors': email_errors,
                'username_errors': username_errors,
                'password_errors': password_errors
            }
        )


class UserSettingsView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        context = {
            "user_form": UpdateUserForm(instance=request.user),
            "profile_form": UpdateProfileForm(instance=request.user)
        }
        return render(request, 'users/settings.html', context)

    def post(self, request, *args, **kwargs):
        u_form = UpdateUserForm(request.POST, instance=request.user)
        p_form = UpdateProfileForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, message="Updated!")
            return redirect("user:settings")
        return self.get(request)


class UserProfileView(View):
    def get(self, request, username, *args, **kwargs):
        return render(request, "users/profile.html", {"user": User.objects.filter(username=username).first()})


class FollowUserView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        target_id = int(request.POST.get('id'))
        target_user = User.objects.filter(id=target_id).first()
        initiator_user = self.request.user
        # инициатор подписывается на таргет
        # пользователь уже подписан -> отписка
        flw = False
        if target_user.profile.followers.filter(id=initiator_user.id).exists():
            target_user.profile.followers.remove(initiator_user)
            initiator_user.profile.following.remove(target_user)
            flw = False
        # подписка
        else:
            initiator_user.profile.following.add(target_user)
            target_user.profile.followers.add(initiator_user)
            flw = True

        result = target_user.profile.followers_count
        initiator_user.profile.save()
        target_user.profile.save()
        return JsonResponse({"result": result, 'flw': flw})


class UserFollowerView(LoginRequiredMixin, View):
    def get(self, request, username, *args, **kwargs):
        user = User.objects.filter(username=username).first()
        users = user.profile.followers.all()
        return render(
            request,
            'users/followers.html',
            {
                'users': users,
                'target': 'Followers'
            }
        )


class UserFollowingView(LoginRequiredMixin, View):
    def get(self, request, username, *args, **kwargs):
        user = User.objects.filter(username=username).first()
        users = user.profile.following.all()
        return render(
            request,
            'users/followers.html',
            {
                'users': users,
                'target': 'Following'
            }
        )

users/templates/users/followers.html
{% extends 'instagram/layout.html' %}
{% load static %}
{% block content %}
<h3>{{target}}</h3>
<table class="table">
    <thead>
        <tr>
            <th>Username</th>
            <th>Followers</th>
            <th>Following</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td><img src="{{ request.user.profile.image.url }}" alt="..."
                    style="width: 36px;height: 36px;border-radius: 50%;margin-right: 5px;"><a
                    href="{% url 'user:profile' user.username %}">{{user.username}}</a></td>
            <td><b style="font-size: 22px;">{{ user.profile.followers_count }}</b></td>
            <td><b style="font-size: 22px;">{{ user.profile.following_count }}</b></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <title>Instagram</title>
</head>

<style>
    .login {
        min-height: 50vh;
    }

    .bg-image {
        background-image: url('https://source.unsplash.com/WEQbe2jBg40/600x1200');
        background-size: cover;
        background-position: center;
    }

    .login-heading {
        font-weight: 300;
    }

    .btn-login {
        font-size: 0.9rem;
        letter-spacing: 0.05rem;
        padding: 0.75rem 1rem;
    }
</style>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'instagram:home' %}">Instagram</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <div class="dropdown">
                            <img src="{{ request.user.profile.image.url }}" alt="..."
                                style="width: 36px;height: 36px;border-radius: 50%;margin-right: 5px;" type="button"
                                id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="nav-item nav-link" href="{% url 'instagram:post-create' %}">New Post</a>
                                </li>
                                <li><a class="nav-item nav-link" href="{% url 'user:settings' %}">Settings</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="nav-item nav-link" href="{% url 'logout' %}">Sign Out</a></li>
                            </ul>
                        </div>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <form class="d-flex" style="margin-top:2px">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                                id="isearch" style="position: relative;" data-toggle="dropdown">
                            <div class="dropdown">
                                <ul class="dropdown-menu" role="menu" aria-labelledby="menu1" id="drp">
                                </ul>
                            </div>
                        </form>
                    </li>
                    {% if user.is_authenticated %}
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="{% url 'user:register' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="{% url 'user:login' %}">Sign In</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
        <div class="container-fluid ps-md-0">
            <div class="row g-0">
                <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
                <div class="col-md-8 col-lg-6">
                    <div class="login d-flex align-items-center py-5">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-9 col-lg-8 mx-auto">
                                    <h3 class="login-heading mb-4">Welcome Back!</h3>
                                    <!-- Sign In Form -->
                                    <form action="" method="POST">
                                        {%csrf_token%}
                                        <div class="form-floating mb-3">
                                            <small class="text-muted">Username</small>
                                            {{form.username}}
                                        </div>
                                        <div class="form-floating mb-3">
                                            <small class="text-muted">Password</small>
                                            {{form.password}}
                                        </div>

                                        <div class="d-grid">
                                            <button class="btn btn-lg btn-primary btn-login text-uppercase fw-bold mb-2"
                                                type="submit" style="height: 35px;">Sign
                                                In</button>
                                            <div class="text-center">
                                                <a class="small" href="{% url 'user:register' %}">Haven't got an account yet?</a>
                                            </div>
                                        </div>
                                        <div>
                                            {% if errors %}
                                                {% for error in errors %}
                                                    <small style="color: red;">{{error}}</small>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script> -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

users/templates/users/logout.html
{% extends "instagram/layout.html" %}
{% block content %}
<h2>You have been signed out</h2>
    <div class="border-top pt-3">
        <small class="text-muted"><a href="{% url 'user:login' %}">Sign in again </a></small>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "instagram/layout.html" %}
<!--  -->
{% load crispy_forms_tags %}
<!-- user vars -->
{% load user_tags %} 
<!--  -->
{% get_user_posts user as posts %}
<!--  -->
{% load static %}
{% block content %}

<div class="row">
  <img src="{{user.profile.bg_image.url}}" alt="" style="max-height: 350px;" />
</div>
<div class="row" style="position: relative; margin-bottom: 1vh;">
  <div class="col-sm">
    <div class="img-circle">
      <img src="{{user.profile.image.url}}" alt="" />
    </div>
  </div>
  <div class="col-sm" style="text-align: right;">
    {% if request.user == user %}
    <a href="{% url 'user:settings' %}" class="Mybtn">
      <small>Edit Profile</small>
    </a>
    {% else %} {% is_following request.user user as flw %} {% if flw %}
    <button id="follow-btn" class="btn-uf" value="{{ user.id }}">
      <small id="btn-txt">Unfollow</small>
    </button>
    {% else %}
    <button id="follow-btn" class="btn-f" value="{{ user.id }}">
      <small id="btn-txt">Follow</small>
    </button>
    {% endif %} {% endif %}
    {% if request.user != user %}
      <a href="{% url 'chat:chats-create' who=request.user.username _with=user.username %}">Send Message</a>
    {% endif %}
  </div>
</div>
<div class="row mr-2">
  <div class="col-sm">
    <b style="font-size: x-large;">{{user.first_name}}</b>
    <small>@{{user.username}}</small>
  </div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
</div>
<div class="row mb-4">
  <div class="col-sm">
    <small id="followers" style="font-size: 14px;">
      {{user.profile.followers.count}} Followers
    </small>
    <small style="font-size: 14px;">
      {{user.profile.following.count}} Following
    </small>
  </div>
</div>
<hr />
<div class="row">
  {% for post in posts %}
  <div class="col-lg-6 mb-1" style="padding: 2px;">
    <a href="{% url 'instagram:post-detail' post.id %}">
      <img
        src="{{post.image.url}}"
        alt=""
        class="img-fluid rounded shadow-sm"
      />
    </a>
  </div>
  {% endfor %}
</div>
<script>
  function getCookie(name) {
    var cookieValue = null
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';')
      for (var i = 0; i < cookies.length; i++) {
        var cookie = jQuery.trim(cookies[i])
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === name + '=') {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1))
          break
        }
      }
    }
    return cookieValue
  }
  $(document).on('click', '#follow-btn', (e) => {
    e.preventDefault()
    $.ajax({
      type: 'POST',
      url: '{% url "user:follow" %}',
      data: {
        id: $('#follow-btn').val(),
        csrfmiddlewaretoken: getCookie('csrftoken'),
        action: 'post',
      },
      success: (json) => {
        document.getElementById('followers').innerHTML =
          json['result'] + ' Followers'
        cls = ''
        if (json['flw']) {
          cls = 'btn-uf'
          txt = 'Unfollow'
        } else {
          cls = 'btn-f'
          txt = 'Follow'
        }
        document.getElementById('follow-btn').className = cls
        document.getElementById('btn-txt').innerHTML = txt
      },
      error: (xhr, errmsg, err) => {},
    })
  })
</script>
{% endblock content %}

users/templates/users/settings.html
{% extends 'instagram/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {%csrf_token%}

    <fieldset class="form-group">
        <legend class="border-bottom mb-4">
            Profile Info
        </legend>
        {{ user_form|crispy }}
        {{ profile_form|crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Update</button>
    </div>
</form>
{% endblock content %}